document.addEventListener('DOMContentLoaded', () => {
    // We will fetch the local JSON files generated by our pipeline.
    // Note: Due to CORS, opening index.html directly from the file system might block fetch requests.
    // Using a local server or IDE preview is recommended.
    
    fetchTestResults();
    fetchZapResults();
});

async function fetchTestResults() {
    try {
        if (!window.testData || Object.keys(window.testData).length === 0) {
            throw new Error('Report data not generated yet.');
        }
        const data = window.testData;
        
        // Update Stats
        document.getElementById('totalTests').innerText = data.total || 0;
        
        const passedEl = document.getElementById('passedTests');
        passedEl.innerText = 0;
        animateValue(passedEl, 0, data.passed || 0, 1500);

        const failedEl = document.getElementById('failedTests');
        failedEl.innerText = 0;
        animateValue(failedEl, 0, data.failed || 0, 1500);

        // Progress bar
        const total = data.total || 1; // avoid div by zero
        const passPercentage = ((data.passed || 0) / total) * 100;
        const bar = document.getElementById('testProgressBar');
        setTimeout(() => {
            bar.style.width = passPercentage + '%';
            if(passPercentage < 100) {
                bar.style.background = 'linear-gradient(90deg, #ef4444, #f87171)'; // Red if any failed
            }
        }, 800);

        // Update Table
        const tbody = document.getElementById('testResultsBody');
        tbody.innerHTML = '';
        
        data.tests.forEach((test, index) => {
            const tr = document.createElement('tr');
            tr.style.animation = `fadeUp 0.5s ease forwards ${index * 0.1}s`;
            tr.style.opacity = '0';
            
            tr.innerHTML = `
                <td style="color: #e2e8f0; font-weight: 600;">${test.testName}</td>
                <td style="font-family: 'Outfit', sans-serif;">${test.description}</td>
                <td>${test.durationMs}ms</td>
                <td><span class="status-badge ${test.status}">${test.status}</span></td>
            `;
            tbody.appendChild(tr);
        });

    } catch (error) {
        console.error('Error fetching test results:', error);
        document.getElementById('totalTests').innerText = '0';
        document.getElementById('passedTests').innerText = '0';
        document.getElementById('failedTests').innerText = '0';
    }
}

async function fetchZapResults() {
    try {
        if (!window.zapData || Object.keys(window.zapData).length === 0) {
            throw new Error('ZAP report data not generated yet.');
        }
        const data = window.zapData;
        
        // Count alerts
        let alertCount = 0;
        if(data.site && data.site[0] && data.site[0].alerts) {
            alertCount = data.site[0].alerts.length;
        }

        const alertsEl = document.getElementById('securityAlerts');
        alertsEl.innerText = 0;
        animateValue(alertsEl, 0, alertCount, 1500);

        const statusEl = document.getElementById('securityStatus');
        setTimeout(() => {
            if(alertCount > 0) {
                statusEl.innerHTML = `<i class="fa-solid fa-triangle-exclamation" style="color: var(--warning)"></i> ${alertCount} vulnerabilities found.`;
                statusEl.style.color = 'var(--warning)';
            } else {
                statusEl.innerHTML = `<i class="fa-solid fa-shield-check" style="color: var(--success)"></i> Code is secure.`;
                statusEl.style.color = 'var(--success)';
            }
        }, 1500);

    } catch (error) {
        console.error('Error fetching ZAP results:', error);
        document.getElementById('securityAlerts').innerText = '0';
        document.getElementById('securityStatus').innerText = 'Scan data not available.';
    }
}

// Helper animation for numbers
function animateValue(obj, start, end, duration) {
    let startTimestamp = null;
    const step = (timestamp) => {
        if (!startTimestamp) startTimestamp = timestamp;
        const progress = Math.min((timestamp - startTimestamp) / duration, 1);
        obj.innerHTML = Math.floor(progress * (end - start) + start);
        if (progress < 1) {
            window.requestAnimationFrame(step);
        }
    };
    window.requestAnimationFrame(step);
}

// Add a quick fade-up animation to the document style
const style = document.createElement('style');
style.innerHTML = `
@keyframes fadeUp {
    from { opacity: 0; transform: translateY(10px); }
    to { opacity: 1; transform: translateY(0); }
}
`;
document.head.appendChild(style);
